AllCops:
  TargetRubyVersion: 3.0

Metrics/AbcSize:
  CountRepeatedAttributes: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
